# Generated by Django 5.0.1 on 2024-02-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0002_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='category',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
