# Generated by Django 5.0.1 on 2024-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0003_pet_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_category', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
