# Generated by Django 5.0.1 on 2024-02-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0006_rename_pet_category_petcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
