# Generated by Django 5.0.1 on 2024-02-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0013_cartitem_pet_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
